### PR TITLE
* Added MIDI channel info to MIDI message description

### PR DESCRIPTION
**Pull request by erroreyes**
* Minor UI and font size changes to label, font size change to message box text

### CODE REVIEW

**Comment by erroreyes** [comment]
Added MIDI channel info and minor UI updates.

**Comment by baconpaul** [comment]
Happy to merge if you want but you closed it. Let me know!

I had forgotten about this utility :)

**Comment by erroreyes** [comment]
Ah oops. I see that I did close it. I'm trying to reacquaint myself with Git, and I overshot a little.

If this is useful, then a merge would be cool. I added the MIDI channel information because I needed a monitoring tool in Linux that could help me understand a feature in Bitwig that was throwing me off.

**Comment by baconpaul** [comment]
Great! Well thanks for adding it here!

**Pull request merged**
